### ISSUE TITLE
some more details about perf.txt...

### ISSUE THREAD

**Issue by hsiangkao** [ericcurtin/staging#1]
Hi @ericcurtin,

I observed the test results of https://github.com/ericcurtin/staging/blob/63eaabc2f9826bfbcc6eb0ad48362d908ff1d379/perf.txt
Could you help provide the datasets and test scripts so I can find out what happened on the read time?

**Comment by ericcurtin** [comment]
Hey @hsiangkao my staging git repo is really a dumping ground... It's almost a backup repo if my machine blows up, etc.

Looking at the git commit it's the testing result of this script:

https://github.com/ericcurtin/staging/blob/master/hello.sh

I suspect 1G.txt what just a randomly generated 1G file

**Comment by hsiangkao** [comment]
> Hey @hsiangkao my staging git repo is really a dumping ground... It's almost a backup repo if my machine blows up, etc.
> 
> Looking at the git commit it's the testing result of this script:
> 
> https://github.com/ericcurtin/staging/blob/master/hello.sh
> 
> I suspect 1G.txt what just a randomly generated 1G file

Thanks for the reply, does the test script retest ext4 as erofs, so I'm afraid it reuses erofs warm cache?

```
printf "erofs\nmount time: "
time sudo mount /dev/loop1 erofs
printf "read time:  "
time sudo cat erofs/1G.txt > /dev/null
printf "ext4\nmount time: "
time sudo mount /dev/loop3 ext4
printf "read time:  "
time sudo cat erofs/1G.txt > /dev/null       <--- here
echo
```

**Comment by ericcurtin** [comment]
> > Hey @hsiangkao my staging git repo is really a dumping ground... It's almost a backup repo if my machine blows up, etc.
> > Looking at the git commit it's the testing result of this script:
> > https://github.com/ericcurtin/staging/blob/master/hello.sh
> > I suspect 1G.txt what just a randomly generated 1G file
> 
> Thanks for the reply, does the test script retest ext4 as erofs, so I'm afraid it reuses erofs warm cache?
> 
> ```
> printf "erofs\nmount time: "
> time sudo mount /dev/loop1 erofs
> printf "read time:  "
> time sudo cat erofs/1G.txt > /dev/null
> printf "ext4\nmount time: "
> time sudo mount /dev/loop3 ext4
> printf "read time:  "
> time sudo cat erofs/1G.txt > /dev/null       <--- here
> echo
> ```

Yes well spotted that's an issue... Measuring the wrong things

It wouldn't have mattered anyway, I didn't go far with this. This "staging" repo is really a dumping groud for me.

Sometimes this dumping ground ends up being things I actually use, but most of the time no...

**Comment by hsiangkao** [comment]
okay, let me close this issue, thanks! 👍
